hackclub/blot

src/apps/editor/src/Editor.module.css, src/apps/editor/src/Editor.tsx, src/apps/editor/src/components/BezierEditor.module.css, src/apps/editor/src/components/BezierEditor.tsx, src/apps/editor/src/components/CodeMirror.tsx, src/apps/editor/src/components/Console.tsx, src/apps/editor/src/components/Error.module.css, src/apps/editor/src/components/Error.tsx, src/apps/editor/src/components/Preview.tsx, src/apps/editor/src/components/ScalableCanvas.module.css, src/apps/editor/src/components/ScalableCanvas.tsx, src/apps/editor/src/components/Toolbar.module.css, src/apps/editor/src/components/Toolbar.tsx, src/apps/editor/src/lib/codemirror/liveUpdate.ts, src/apps/editor/src/lib/codemirror/numberScrubbing.ts, src/apps/editor/src/lib/codemirror/state.ts, src/apps/editor/src/lib/codemirror/utils.ts, src/apps/editor/src/lib/codemirror/widgets.module.css, src/apps/editor/src/lib/codemirror/widgets.tsx, src/apps/editor/src/lib/download.ts, src/apps/editor/src/lib/downloadPng.ts, src/apps/editor/src/lib/downloadSvg.ts, src/apps/editor/src/lib/run.ts, src/apps/editor/src/lib/state.ts, src/apps/editor/src/ui/3DCurveManualIcon.tsx, src/apps/editor/src/ui/CloseIcon.tsx, src/apps/editor/src/ui/Dropdown.module.css, src/apps/editor/src/ui/Dropdown.tsx
=> Bezier widget

guides/tree.md
=> Update editor link in tree.md

art/eca-henry/eca.js, art/landscape-henry/index.js, art/raymarching-henry/raymarch.js, astro/src/lib/drawingToolkit/turtle.ts, astro/src/lib/events/addMachineControl.js, astro/src/lib/haxidraw/createHaxidraw.js, guides/10PRINT.md, guides/10PRINT2.md, guides/cubic_disarray.md, guides/eca.md, guides/joydivision.md, guides/landscape.md, guides/mesh.md, guides/raymarching.md, guides/toolkit/toolkit.md, virtual-gallery/drawing-functions/Turtle.js
=> made goTo function camelcase

astro/src/lib/events/addMachineControl.js, docs/ENGAGEMENT.md
I updated the browser warning and the Engagement.md
=> update browser compatibly warning and ENGAGEMENT.MD

astro/src/components/standard-head.astro, astro/src/layouts/Layout.astro
=> Adding metadata to the site

astro/src/pages/index.astro
Adds the ability to preview the blot in AR
https://github.com/hackclub/blot/assets/5891442/c560a2ba-27ae-4c75-98d7-4b58ad9f8976
=> Add AR view to homepage

docs/TUNING.md
https://hackclub.slack.com/archives/C04GCH8A91D/p1707183245832409
=> Add Drawing Instructions

astro/astro.config.mjs, astro/src/components/Navbar.astro, astro/src/pages/assembly.astro, astro/src/pages/index.astro
This means the link is only in once place and less likely something we can screw up by partially updating
=> Assembly page is astro-configured redirect

docs/packaging/notecard.js
done as requested by @maxwofford on slack :) https://hackclub.slack.com/archives/C04GCH8A91D/p1707948489371829
test here: [https://blot.hackclub.dev/editor?src=https://raw.githubusercontent.com/hackclub/blot/521d190f5b00342656f4089d35773f45b91ee2c9/docs/packaging/notecard.js](https://blot.hackclub.dev/editor?src=https://raw.githubusercontent.com/hackclub/blot/521d190f5b00342656f4089d35773f45b91ee2c9/docs/packaging/notecard.js)
=> feat: updated blot font in the packing notecard script

docs/ASSEMBLY.md
=> Add instructions on fixing v-wheels

docs/TUNING.md
=> Add wiring to TUNING.md

README.md
Fixed The Word Are to Art in the readme
=> Minor Grammar Change In Readme

docs/TUNING.md
Add belt tightening related stuff to the tuning guide
=> Add some stuff to tuning guide

public/getting-started/index.md
=> Typo in start guide

src/drawingToolkit/cutCover.js
Since addToNdp causes issue #392 and replacing it with vanilla ndp.push doesn't (seem to) break anything, provisionally replaced it.
=> Replace addToNdp with ndp.push

docs/GET_A_BLOT.md
I noticed it said "Your artwork must be original." twice.
=> Removed duplicate criteria from "GET_A_BLOT.md".

src/makeIncluded.js
=> add warning on Math.random()

.github/workflows/art-pr.yml
adds comments with editor links for PRs with `index.js` files in the `/art` directory
closes #691
=> add preview link gh action

src/components/DropBox.tsx
add copy button to SVG import - makes it way easier to copy and paste the content into the editor
improve terminology - this makes the UI easier to understand
remove unnecessary errors - Default to sensible values when there is invalid input instead of erroring
This also removes some of the random extra whitespace i accidentally added with my last PR, sorry about that
=> General improvements to editor

docs/DOCUMENTATION.md
I think that adding the links to Wikipedia will help understand what are the curve types.
=> Add links to wikipedia to explain curve types

api/index.js, build.js, server.js, vercel.json
- build.js should do all the building, not server.js (???)
- added vercel.json w/ vercel config
- separated out express stuff so it can be run both locally and on vercel
=> make ready to deploy on vercel

src/components/Toolbar.tsx
basically i added a slight margin between the icon and the name on the header of the blot editor. it should look slightly more aesthetically pleasing now. please let this go through this has been bugging me for two weeks. 
i need sleep (it is 5:39 am rn. yes it took 8 min to figure out how to get the pull request working. no i have no idea how it works but im writing this comment so it must be working.)
thanks.
=> [editor header] finally fixed up the hecking ui at 5:31 am

.github/PULL_REQUEST_TEMPLATE.md
Write a short description about your art piece, such as what your artwork represents and your experience drawing it!
Next, make sure you go through **each item** in the following checklist. Delete this line after!
If you used based your art on something else, used a tutorial, or remixed it from something else, please link it here:
Lastly, link a picture of your art piece here:
=> Update PULL_REQUEST_TEMPLATE.md 

art/Birb-AyaanGrover/index.js
I updated the link to my artwork's snapshot.
=> Update Snapshot Link

docs/assembly/ASSEMBLY.md
I fixed a typo/error in the build instructions.
=> fix: error in ASSEMBLY.md

src/drawingToolkit/toolkit.js
its written in the docs
https://blot.hackclub.com/docs
=> add xor function
